version: '3'
services:
  master_api:
    build: .
    ports:
      - "8001:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - my-network

  worker-1:
    image: cc_assignment_3
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - my-network

  worker-2:
    image: cc_assignment_3
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - my-network

  worker-3:
    image: cc_assignment_3
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
